In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
data = pd.read_excel('Simmons.xls')
data.head()

,Customer,Spending,Card,Coupon
0,1,2.291,1,0
1,2,3.215,1,0
2,3,2.135,1,0
3,4,3.924,0,0
4,5,2.528,1,0


In [5]:
data.describe()   # It is used to get some statistical detail

,Customer,Spending,Card,Coupon
count,100.000000,100.000000,100.000000,100.000000
mean,50.500000,3.333790,0.500000,0.400000
std,29.011492,1.741298,0.502519,0.492366
min,1.000000,1.058000,0.000000,0.000000
25%,25.750000,2.059000,0.000000,0.000000
50%,50.500000,2.805500,0.500000,0.000000
75%,75.250000,4.468250,1.000000,1.000000
max,100.000000,7.076000,1.000000,1.000000


In [6]:
data['Coupon'].unique()   # It gives unique value in perticular column
data['Coupon'].value_counts()

Coupon
0    60
1    40
Name: count, dtype: int64

In [7]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [8]:
x = data[['Card', 'Spending']]
y = data['Coupon'].values.reshape(-1, 1)

In [9]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.25, random_state=42
)

In [10]:
len(x_train), len(y_train), len(x_test), len(y_test)

(75, 75, 25, 25)

In [11]:
Lreg = LogisticRegression(solver='lbfgs')
Lreg.fit(x_train, y_train.ravel())   # Ravel() will return 1D array

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [12]:
y_predict = Lreg.predict(x_test)
y_predict

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0])

In [13]:
y_predict_train = Lreg.predict(x_train)
y_predict_train

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0])

In [14]:
y_prob_train = Lreg.predict_proba(x_train)[:, 1]
y_prob_train.reshape(1, -1)

array([[0.49618288, 0.32880558, 0.44331124, 0.33320598, 0.41459023,
        0.32890093, 0.39748721, 0.66918819, 0.25845659, 0.63670531,
        0.29274878, 0.28467622, 0.51588732, 0.41994733, 0.24343741,
        0.5285169 , 0.47961622, 0.52801323, 0.3319115 , 0.27458272,
        0.49175558, 0.6325985 , 0.24691508, 0.47090915, 0.27842841,
        0.41661746, 0.36154674, 0.49971207, 0.23623138, 0.37863254,
        0.48810439, 0.28878446, 0.28564488, 0.3723519 , 0.65307608,
        0.43809375, 0.33638085, 0.40409358, 0.23432709, 0.37285684,
        0.49971207, 0.39771263, 0.32880558, 0.25783611, 0.47390468,
        0.4288115 , 0.26521947, 0.33320598, 0.54682415, 0.45447877,
        0.44323889, 0.49652615, 0.60064794, 0.3899266 , 0.49150494,
        0.27415269, 0.27786462, 0.67461641, 0.28195703, 0.48594587,
        0.38631757, 0.31373574, 0.42812388, 0.27419567, 0.44373772,
        0.41632126, 0.64198463, 0.65707806, 0.44070086, 0.28195703,
        0.40215203, 0.43809375, 0.50973548, 0.57

In [15]:
y_prob = Lreg.predict_proba(x_test)[:, 1]
y_prob.reshape(1, -1)

array([[0.52803246, 0.49517625, 0.45705046, 0.27712842, 0.34389496,
        0.26826124, 0.27712842, 0.60767304, 0.42838832, 0.43639299,
        0.31387527, 0.23677742, 0.45705046, 0.43600217, 0.37599363,
        0.44902215, 0.46949093, 0.68519265, 0.251685  , 0.47074771,
        0.42363481, 0.56580175, 0.5279248 , 0.40305375, 0.27458272]])

In [16]:
# Summary for logistic model
x = data[['Spending', 'Card']]
y = data['Coupon']

In [17]:
import statsmodels.api as sm

In [18]:
x1 = sm.add_constant(x)
logit_model = sm.Logit(y, x1)
result = logit_model.fit()

Optimization terminated successfully.
         Current function value: 0.604869
         Iterations 5


In [19]:
print(result.summary())

                           Logit Regression Results                           
Dep. Variable:                 Coupon   No. Observations:                  100
Model:                          Logit   Df Residuals:                       97
Method:                           MLE   Df Model:                            2
Date:                Tue, 31 Mar 2026   Pseudo R-squ.:                  0.1012
Time:                        23:20:07   Log-Likelihood:                -60.487
converged:                       True   LL-Null:                       -67.301
Covariance Type:            nonrobust   LLR p-value:                  0.001098
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -2.1464      0.577     -3.718      0.000      -3.278      -1.015
Spending       0.3416      0.129      2.655      0.008       0.089       0.594
Card           1.0987      0.445      2.471      0.0

In [20]:
from sklearn.metrics import accuracy_score

In [21]:
score = accuracy_score(y_test, y_predict)
score

0.76

In [22]:
from sklearn.metrics import confusion_matrix

In [23]:
confusion_matrix(y_test, y_predict)

array([[15,  1],
       [ 5,  4]])

In [24]:
tn, fp, fn, tp = confusion_matrix(y_test, y_predict).ravel()

In [25]:
print("True Negatives: ", tn)
print("False Positives: ", fp)
print("False Negatives: ", fn)
print("True Positives: ", tp)

True Negatives:  15
False Positives:  1
False Negatives:  5
True Positives:  4


In [26]:
from sklearn.metrics import classification_report

In [27]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.75      0.94      0.83        16
           1       0.80      0.44      0.57         9

    accuracy                           0.76        25
   macro avg       0.78      0.69      0.70        25
weighted avg       0.77      0.76      0.74        25

